// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student_service.proto

package student.poc.grpc;

public final class StudentServiceOuterClass {
  private StudentServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_student_poc_grpc_StudentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_student_poc_grpc_StudentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_student_poc_grpc_Address_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_student_poc_grpc_Address_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_student_poc_grpc_StudentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_student_poc_grpc_StudentResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025student_service.proto\022\020student.poc.grp" +
      "c\"u\n\016StudentRequest\022\021\n\tfirstName\030\001 \001(\t\022\020" +
      "\n\010lastName\030\002 \001(\t\022\022\n\nroleNumber\030\003 \001(\005\022*\n\007" +
      "address\030\004 \003(\0132\031.student.poc.grpc.Address" +
      "\"7\n\007Address\022\r\n\005state\030\001 \001(\t\022\020\n\010district\030\002" +
      " \001(\t\022\013\n\003pin\030\003 \001(\005\")\n\017StudentResponse\022\026\n\016" +
      "studentDetails\030\001 \001(\t2c\n\016StudentService\022Q" +
      "\n\naddStudent\022 .student.poc.grpc.StudentR" +
      "equest\032!.student.poc.grpc.StudentRespons" +
      "eB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_student_poc_grpc_StudentRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_student_poc_grpc_StudentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_student_poc_grpc_StudentRequest_descriptor,
        new java.lang.String[] { "FirstName", "LastName", "RoleNumber", "Address", });
    internal_static_student_poc_grpc_Address_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_student_poc_grpc_Address_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_student_poc_grpc_Address_descriptor,
        new java.lang.String[] { "State", "District", "Pin", });
    internal_static_student_poc_grpc_StudentResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_student_poc_grpc_StudentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_student_poc_grpc_StudentResponse_descriptor,
        new java.lang.String[] { "StudentDetails", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
