// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student_service.proto

package student.poc.grpc;

public interface StudentResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:student.poc.grpc.StudentResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string studentDetails = 1;</code>
   * @return The studentDetails.
   */
  java.lang.String getStudentDetails();
  /**
   * <code>string studentDetails = 1;</code>
   * @return The bytes for studentDetails.
   */
  com.google.protobuf.ByteString
      getStudentDetailsBytes();
}
